// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadXdpTcp returns the embedded CollectionSpec for XdpTcp.
func LoadXdpTcp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpTcpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load XdpTcp: %w", err)
	}

	return spec, err
}

// LoadXdpTcpObjects loads XdpTcp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XdpTcpObjects
//	*XdpTcpPrograms
//	*XdpTcpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXdpTcpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXdpTcp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XdpTcpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpTcpSpecs struct {
	XdpTcpProgramSpecs
	XdpTcpMapSpecs
	XdpTcpVariableSpecs
}

// XdpTcpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpTcpProgramSpecs struct {
	XdpTcpParser *ebpf.ProgramSpec `ebpf:"xdp_tcp_parser"`
}

// XdpTcpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpTcpMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// XdpTcpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpTcpVariableSpecs struct {
}

// XdpTcpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXdpTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpTcpObjects struct {
	XdpTcpPrograms
	XdpTcpMaps
	XdpTcpVariables
}

func (o *XdpTcpObjects) Close() error {
	return _XdpTcpClose(
		&o.XdpTcpPrograms,
		&o.XdpTcpMaps,
	)
}

// XdpTcpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXdpTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpTcpMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *XdpTcpMaps) Close() error {
	return _XdpTcpClose(
		m.Events,
	)
}

// XdpTcpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadXdpTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpTcpVariables struct {
}

// XdpTcpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXdpTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpTcpPrograms struct {
	XdpTcpParser *ebpf.Program `ebpf:"xdp_tcp_parser"`
}

func (p *XdpTcpPrograms) Close() error {
	return _XdpTcpClose(
		p.XdpTcpParser,
	)
}

func _XdpTcpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdptcp_bpfeb.o
var _XdpTcpBytes []byte
